# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: SOFT806

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore SOFT806/
    - name: Build
      run: dotnet build SOFT806/ --no-restore
    - name: Test
      run: dotnet test SOFT806/ --no-build --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish SOFT806/ --no-build --no-restore --verbosity normal
      
